apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-pytorch
spec:
  template:
    spec:
      containers:
        - name: classifier-pytorch
          env:
            - name: DUMMY_MODE
              value: "false"
            - name: CLASSIFIER_MODEL_URI
              value: "models:/tone-classifier@canary"
            - name: DEPLOYMENT_TIER
              value: "canary"
